FROM golang:1.16-alpine as build
WORKDIR /app
COPY go.mod .
RUN go mod download
COPY *.go ./
RUN go build -o /server


FROM alpine
COPY --from=build /server /server
EXPOSE 8080
ENTRYPOINT [ "/server" ]